### ISSUE TITLE
qoob on page builder not loading.

### ISSUE THREAD

**Issue by evripides** [webarkio/wp_qoob#22]
hi
i have latest wordpress with qoob them install
when i load a page and click on qoob editor
loads until 33
php 5.5.6
can u help
thanks

**Comment by Alecto** [comment]
the same for me.
at one site the qoob works (the plugin was installed since version 2.0.4 and then it was updated to 2.0.6).

on the same hosting I added a new website: wordpress 4.8.1, the latest version of qoob , php 7.1.
Page does not load.
33% and there is no further progress.
No libs connected, nothing... only clear standart WP and qoob.

http://savepic.net/9780817.gif

**Comment by evripides** [comment]
same for me 
i try to 3 different websites the plugin
we wait to the owner to respond

**Comment by portapro** [comment]
Hi. We're working on this problem now. We'll update the current version and this bug will be fixed. Regards

**Comment by evripides** [comment]
thanks hope u fix it soon so we build our website
have a great day

**Comment by Alecto** [comment]
page loading at 2 sites with qoob, thank U!
at one test site, accessible via protocol HTTP qoob works properly.

at other site, accessible via httpS - qoob doesnt work.
details here https://github.com/webarkio/wp_qoob/issues/23

**Comment by portapro** [comment]
#23
